
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dekrcoiaoiamjyckagug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRla3Jjb2lhb2lhbWp5Y2thZ3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDkxMjIsImV4cCI6MjA2MjkyNTEyMn0.nxbVm_f4kl4fnkPr30By6Lg1l9B_p6kZy1udHykBxnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
